ToDoApp/ToDoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist.views import todoview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', todoview, name='index'),
    path('todolist/', include('todolist.urls')),
    path('account/', include('account.urls'))
]

ToDoApp/account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns=[
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

ToDoApp/todolist/urls.py
from django.urls import path
from . import views

app_name='todolist'

urlpatterns=[
    path('', views.todoview, name='todoview'),
    path('about/', views.about, name='about'),
    path('checkoff/<list_id>', views.checkOff, name='checkoff'),
    path('checkon/<list_id>',views.checkOn, name='checkon'),
    path('delete/<list_id>', views.delete, name='delete'),
]

ToDoApp/account/models.py
from django.db import models

# Create your models here.

ToDoApp/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    item=models.CharField(max_length=240)
    status=models.BooleanField(default=False)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.item

ToDoApp/todolist/forms.py
from django import forms
from .models import ToDoList

class FormToDoList(forms.ModelForm):
    class Meta:
        model=ToDoList
        fields=['item','status',]

ToDoApp/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(req):
    if req.method == "POST":
        froms=UserCreationForm(req.POST)
        if froms.is_valid:
            user=froms.save()
            login(req,user)
            return redirect('todolist:todoview')
        return render(req, 'account/signup.html', {'forms':froms})
    else:
        forms=UserCreationForm()
        return render(req, 'account/signup.html', {'forms':forms})

def login_view(req):
    if req.method == "POST":
        forms=AuthenticationForm(data=req.POST)
        if forms.is_valid():
            # login
            user=forms.get_user()
            login(req, user)
    return redirect('index')


def logout_view(req):
    if req.user.is_authenticated:
        logout(req)
    return redirect('index')

ToDoApp/todolist/views.py
from django.shortcuts import render, redirect
from .models import ToDoList
from .forms import FormToDoList
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def todoview(req):
    if req.method=='POST':
        forms=FormToDoList(req.POST or None)

        if forms.is_valid():
            # imp
            inst=forms.save(commit=False)
            inst.user=req.user
            inst.save()

    login_forms=AuthenticationForm()
    if req.user.is_authenticated:
        todo_list=ToDoList.objects.filter(user=req.user)
    else:
        todo_list=None
    return render(req, 'todolist/index.html', {'todo_list': todo_list, 'login_forms':login_forms})

def about(req):
    return render(req, 'todolist/about.html',{})

def checkOff(req, list_id):
    todo_list=ToDoList.objects.get(pk=list_id)
    todo_list.status=False
    todo_list.save()
    return redirect('index')

def checkOn(req, list_id):
    todo_list=ToDoList.objects.get(pk=list_id)
    todo_list.status=True
    todo_list.save()
    return redirect('index')

def delete(req, list_id):
    todo_list=ToDoList.objects.get(pk=list_id)
    todo_list.delete()
    return redirect('index')

ToDoApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo | {% block title %} {% endblock %}</title>
</head>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<body class="blue lighten-4">
    <nav class="blue darken-2">
        <div class="nav-wraper">
            <div class="brand-logo"><i class="material-icons" style="font-size: xx-large; padding-top: 5px; padding-left: 2px;">today</i><span class="flow-text">TODOAPP</span></div>
            <a href="" class="sidenav-trigger" data-target="mobile-links">
                <i class="material-icons">menu</i>
            </a>
            <ul class="right hide-on-med-and-down">
                <li class="z-depth-1"><a href="{% url 'todolist:todoview' %}">Home</a></li>
                <li class="z-depth-1"><a href="{% url 'todolist:about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="z-depth-1"><a href="{% url 'account:logout' %}">Logout</a></li>
                {% else %}
                <li class="z-depth-1"><a href="{% url 'account:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <ul class="sidenav blue darken-2" id="mobile-links">
        <li class=""><a href="{% url 'todolist:todoview' %}">Home</a></li>
        <li class=""><a href="{% url 'todolist:about' %}">About</a></li>
        {% if user.is_authenticated %}
        <li class=""><a href="{% url 'account:logout' %}">Logout</a></li>
        {% else %}
        <li class=""><a href="{% url 'account:signup' %}">Signup</a></li>
        {% endif %}
    </ul>
    <div class="container">
        <br>
        <br>
        <br>
        {% block content %}

        {% endblock %}
    </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
<script>
    var elem = document.querySelector('.sidenav');
    var instance = new M.Sidenav(elem);
    $(document).ready(function(){
        $('.sidenav').sidenav();
    });
</script>
</html>

ToDoApp/templates/todolist/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}

    <h3>About Me</h3>
    <p class="flow-text" >
        Hey, I am beginner <b>DJANGO DEVELOPER</b>. I have created is django application from testing my cunnent skill.
        Repo of the site will be available on my <a href="https://github.com/coderj001/django-responsive-todo-app.git">github</a> and if you
        want to ping me join my <a href="https://discord.gg/PnVQtcu">discord</a>. 
    </p>
    <p class="right flow-text">Thank You</p>
{% endblock %}

ToDoApp/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

<h2>ToDo: ADD</h2>

{% if user.is_authenticated %}

    <form action="{% url 'todolist:todoview' %}" class="center" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col s8 input-field">
                <label for="item"><b>Add Task</b></label>
                <input type="text" name="item">
            </div>
            <div class="col s4">
                <button class="btn-floating btn-large waves-effect waves-light red pulse" type="submit"><i class="material-icons">add</i></button>
            </div>
        </div>
    </form>
    <br>
    <br>

    {% if todo_list %}

        <div class="center">
            <table class="highlight centered responsive-table">
                <thead>
                    <tr>
                        <th><center>ToDo</center></th>
                        <th><center>Status</center></th>
                        <th><center>Delete</center></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in todo_list %}
                        {% if i.status %}
                        <tr>
                            <td style="text-decoration: line-through;"><center>{{ i.item }}</center></td>
                            <td><center><a href="{% url 'todolist:checkoff' i.id %}" style="color: aliceblue;"><button class="btn waves-effect waves-light">REDO</button></a></center></td>
                            <td><center><a href="{% url 'todolist:delete' i.id %}" style="color: aliceblue;"><button class="btn waves-effect waves-light">DELETE</button></a></center></td>
                        </tr>
                        {% else %}
                        <tr>
                            <td><center>{{ i.item }}</center></td>
                            <td><center><a href="{% url 'todolist:checkon' i.id %}" style="color: aliceblue;"><button class="btn waves-effect waves-light">DONE</button></a></center></td>
                            <td><center><a href="{% url 'todolist:delete' i.id %}" style="color: aliceblue;"><button class="btn waves-effect waves-light">DELETE</button></a></center></td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>

    {% endif %}
{% else %}

        {% if login_forms %}
            <form class="center" action="{% url 'account:login' %}" method="POST">
                {% csrf_token %}
                {{login_forms}}
                <input type="submit" name="login" value="login" class="btn red">
            </form>
        {% endif %}

{% endif %}
{% endblock %}